### ISSUE TITLE
Javascript never guarantee order of key:value pairs in object.

### ISSUE THREAD

**Issue by socketpair** [santigimeno/node-ioctl#4]
http://stackoverflow.com/questions/5525795/does-javascript-guarantee-object-property-order

**Comment by santigimeno** [comment]
Closing this as it looks there's nothing actionable. Feel free to reopen though

**Comment by socketpair** [comment]
No. Still not fixed. On the main readme file:

```
// define the "snd_hwdep_info" struct type
var termio = StructType({
    c_iflag : ref.types.ushort,
    c_oflag : ref.types.ushort,
    c_cflag : ref.types.ushort,
    c_lflag : ref.types.ushort,
    c_line : ref.types.uchar,
    c_cc : ArrayType(ref.types.uchar, 8)
});
```

On some day, this example become wrong.

**Comment by santigimeno** [comment]
I don't disagree. Let's reopen this once that day comes.
